2025-07-24 17:32:01,574 INFO    MainThread:26027 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-07-24 17:32:01,575 INFO    MainThread:26027 [wandb_setup.py:_flush():80] Configure stats pid to 26027
2025-07-24 17:32:01,575 INFO    MainThread:26027 [wandb_setup.py:_flush():80] Loading settings from /home/user/.config/wandb/settings
2025-07-24 17:32:01,575 INFO    MainThread:26027 [wandb_setup.py:_flush():80] Loading settings from /home/user/Code/EF-TTS/parler-tts/wandb/settings
2025-07-24 17:32:01,575 INFO    MainThread:26027 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-07-24 17:32:01,575 INFO    MainThread:26027 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/user/Code/EF-TTS/parler-tts/wandb/run-20250724_173201-nghesjtj/logs/debug.log
2025-07-24 17:32:01,575 INFO    MainThread:26027 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/user/Code/EF-TTS/parler-tts/wandb/run-20250724_173201-nghesjtj/logs/debug-internal.log
2025-07-24 17:32:01,575 INFO    MainThread:26027 [wandb_init.py:init():830] calling init triggers
2025-07-24 17:32:01,575 INFO    MainThread:26027 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-07-24 17:32:01,575 INFO    MainThread:26027 [wandb_init.py:init():871] starting backend
2025-07-24 17:32:01,799 INFO    MainThread:26027 [wandb_init.py:init():874] sending inform_init request
2025-07-24 17:32:01,829 INFO    MainThread:26027 [wandb_init.py:init():882] backend started and connected
2025-07-24 17:32:01,832 INFO    MainThread:26027 [wandb_init.py:init():953] updated telemetry
2025-07-24 17:32:01,849 INFO    MainThread:26027 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-07-24 17:32:02,478 INFO    MainThread:26027 [wandb_init.py:init():1029] starting run threads in backend
2025-07-24 17:32:02,528 INFO    MainThread:26027 [wandb_run.py:_console_start():2458] atexit reg
2025-07-24 17:32:02,529 INFO    MainThread:26027 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-07-24 17:32:02,529 INFO    MainThread:26027 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-07-24 17:32:02,529 INFO    MainThread:26027 [wandb_run.py:_redirect():2398] Redirects installed.
2025-07-24 17:32:02,530 INFO    MainThread:26027 [wandb_init.py:init():1075] run started, returning control to user process
2025-07-24 17:32:02,530 INFO    MainThread:26027 [wandb_run.py:_config_callback():1363] config_cb None None {'learning_rate': 0.0001, 'model_name_or_path': 'parler-tts/parler-tts-mini-v1', 'num_train_epochs': 3, 'gradient_accumulation_steps': 8, 'per_device_train_batch_size': 4, 'global_batch_size': 4, 'mixed_precision': 'bf16', 'lr_scheduler_type': 'CONSTANT_WITH_WARMUP', 'warmup_steps': 500, 'freeze_text_encoder': True, 'max_duration_in_seconds': 30, 'weight_decay': 0.01, 'adam_beta1': 0.9, 'adam_beta2': 0.99, 'temperature': 1.0}
2025-07-24 17:32:09,846 INFO    MsgRouterThr:26027 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-07-24 17:32:10,762 ERROR   MainThread:26027 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-24 17:32:10,764 ERROR   MainThread:26027 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-24 17:32:10,765 ERROR   MainThread:26027 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-24 17:32:10,765 ERROR   MainThread:26027 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-24 17:32:10,765 ERROR   MainThread:26027 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/user/Code/EF-TTS/.venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
